### PR TITLE
Add Helpers generation task.

### PR DESCRIPTION
**Pull request by connorshea**
Implements #87.

Right now this is very basic and only includes Kernel to allow for basic methods like `puts` or `raise`, in the future we can update it to include more modules from ActionView and elsewhere.

I also still need to update the tests for this change.

This is the kind of `rbi` it generates for [my Rails app](https://github.com/connorshea/VideoGameList):

```ruby
# typed: strong

module ApplicationHelper
  include Kernel
end

module GamesHelper
  include Kernel
end

module GenresHelper
  include Kernel
end

module HomeHelper
  include Kernel
end

module PlatformsHelper
  include Kernel
end

module SettingsHelper
  include Kernel
end

module DeviseHelper
  include Kernel
end
```

### CODE REVIEW

**Comment by connorshea** [comment]
As far as I can tell, the failures are caused by a change in the upstream Sorbet project?

As for the hack that fixes my issue, I wasn't able to get using a version check to work, so I just ended up trying both and setting the helpers array dependent on which one worked.

**Comment by manhhung741** [comment]
Yep, the test with a previous version of sorbet still passed. I'm glad I had it there.
I messaged the sorbet team about the new error:
https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1563377281497000

**Comment by manhhung741** [comment]
Can you add a test to test the rake task itself? It's worth testing the loading logic. ApplicationController is introduced in Rails 5.0 (or 5.1?), maybe it's a different behavior between different version of Rails.

**Comment by manhhung741** [comment]
I had a PR out to fix the tests for latest version of sorbet.

**Comment by connorshea** [comment]
Are there currently any tests for the other rake tests? I’ll try to get to that tonight.

**Comment by manhhung741** [comment]
Yes, there are! Checkout spec/rake_rails_rbi_models_spec.rb for example

**Comment by connorshea** [comment]
I'm not sure how to get this working, honestly. Regenerating the expectations causes them to return with no helpers, for some reason :/

**Comment by manhhung741** [comment]
:’( I’ll see what I can do to help.

**Comment by manhhung741** [comment]
It might still not load helpers correctly.

**Comment by manhhung741** [comment]
I pushed a fix to your branch that change `ApplicationController` to subclass `ActionController::Base` instead of `ActionController::API`. 
You may need to undo unrelated expected data changes because I fixed the conflicts with sorbet upstream

**Comment by connorshea** [comment]
Yup, looks like it needs to have the expectations updated

**Comment by connorshea** [comment]
@manhhung741 this should be ready to merge now 👍

**Comment by manhhung741** [comment]
Thank you!

**Pull request merged**
