### PR TITLE
support newer type_member syntax with sorbet 0.5.9892+

### LINKED ISSUE #503: regression on update to sorbet 0.5.9892+
**Describe the bug:**
Sorbet 0.5.9892 and above includes sorbet/sorbet#5639 which causes regressions due to the changed `type_member` syntax. As mentioned there, the new syntax is supported on 0.5.9889 and above.

**Steps to reproduce:**
Run `rails_rbi:models` and see an error
```
 sorbet/rails-rbi/models/MODEL.rbi:779: The `type_member` syntax for bounds has changed to use a block instead of keyword args https://srb.help/4021
     779 |  Elem = type_member(fixed: Model)
                               ^^^^^^^^^^^^
```

**Expected behavior:**
No errors.

**Workaround**

Till this is fixed, we're using the following `sed` script:
```
grep -rl 'type_member' sorbet/rails-rbi/models/* | xargs --no-run-if-empty -L1 sed -ri 's/type_member\((.+)\)/type_member {{\1}}/g'
```

### PR DESCRIPTION
**Pull request by ashkulz**
fixes #503

### CODE REVIEW

**Comment by ashkulz** [comment]
@ghiculescu I've split up the PR in logical commits so that it's easier to review :man_shrugging:

**Comment by ghiculescu** [comment]
Thank you!

**Comment by ashkulz** [comment]
Would appreciate a release with this commit :slightly_smiling_face:

**Comment by ghiculescu** [comment]
I am trying to get the gem publishing working. I haven't had much luck so far. For now I'd suggest using a github ref if your gemfile.

**Pull request merged**
