### PR TITLE
Allow symbols to be assignable for AR attributes

### PR DESCRIPTION
**Pull request by mgriisser**
The params for attribute assignment to string DB columns appears to be overly restrictive. 

In principle, I think, you can assign almost any `Object` to these columns, e.g. `model.attr = Object.new` gives something like `attr:  "#<Object:0x00007f94b66f3d10>"`. But I'm not sure a change that general makes sense.

Probably should allow symbols though given their ubiquity and similarity to strings.

### CODE REVIEW

**Comment by manhhung741** [comment]
Thanks for the PR! It makes a lot of sense to be able to assign Symbol to a string attribute.
 
Currently we use the type as both attribute type & assignable type, but Rails do a lot of "conversion" at the assignable type. Maybe we can look up the logic in rails for type conversion and try to mimic that for the general case.

**Comment by manhhung741** [comment]
Can you fix the spec failures? You can run `./spec/bin/update_test_data.sh` to re-record the tests

**Comment by mgriisser** [comment]
Done. Thanks for the heads up on the test regen script! I thought there must be something like that but hadn't had time to look into it/ask about it.

**Comment by manhhung741** [comment]
Thank you!

**Pull request merged**
