### PR TITLE
Add Rails 6.1 support

### PR DESCRIPTION
**Pull request by reneklacan**

### CODE REVIEW

**Comment by manhhung741** [comment]
@reneklacan Thank you for adding Rails 6.1! I've fixed the build error on master; can you rebase your PR on top of it?

**Comment by manhhung741** [comment]
By the way, can you also give me edit permissions to the PR? I can help fixing simple conflicts (like `.travis.yml` case)

**Comment by reneklacan** [comment]
@manhhung741 thanks a lot, I rebased this PR and gave you edit permissions

**Review by manhhung741 — APPROVED** [review]
Thank you :-)

**Pull request merged**
