### PR TITLE
add a rake task to generate jobs file

### LINKED ISSUE #239: Generate perform_now and perform_later
**Describe the ~~bug~~ feature:**

In #238 Harry suggested that we should generate RBI for `perform_now` and `perform_later`.

> For sorbet-rails, I think we can generate perform_later and perform_now class methods based on the manually written signature, much like how we generate delivery method for mailers. If you're interested in doing that, I can give you more direction on how to do it. It should be simple because sorbet-rails already has a library method that extracts sorbet signature from a method

**Steps to reproduce:**

1. `rails g job myjob`
2. set job sigil to `false` or higher
3. `rake rails_rbi:all`
4. `ack perform_now sorbet/rails-rbi` no occurrences

**Expected behavior:**

`rake rails_rbi:all` should generate RBI for `perform_now` and `perform_later`.

**Versions:**

- Ruby: all supported
- Rails: all supported
- Sorbet: all supported
- Sorbet-Rails: future :grin:

### PR DESCRIPTION
**Pull request by manhhung741**
Using `SorbetRails::SorbetUtils.parameters_from_method_def` we can easily generate `perform_now` and `perform_later` for ActiveJob's descendants

This should resolve #239

### CODE REVIEW

**Comment by manhhung741** [comment]
Add a run time test

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/sorbet-rails/compare/d9de7a52a0cacb4bbd2b6b3d6978df0534066e52..355824b136096328cf14bd528ddcff963bdc21e8).

**Comment by manhhung741** [comment]
update params for "set"/

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/sorbet-rails/compare/68cda50fb1e19e002a61c7bf0d160e0577f86c8a..67f7b8bef229e49f6f38e5776b7cd48c72eb48d5).

**Comment by manhhung741** [comment]
update README

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/sorbet-rails/compare/b2b1881ae85437fb49bac272c3551da37fdf87a4..d5db549bd8cd0120a75355f930cf01b92bd23a07).

**Comment by jaredbeck** [comment]
Thanks Harry, looking forward to trying this out!

**Pull request merged**
