### PR TITLE
Fix ActiveRecord::NoEnvironmentInSchemaError message

### PR DESCRIPTION
**Pull request by jasnow**
1. Add 'DISABLE_DATABASE_ENVIRONMENT_CHECK=1' twice to sorbet-rails/spec/bin/run_spec.sh file. This fix gets rid of these messages:
```
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        bin/rails db:environment:set RAILS_ENV=test
```

### CODE REVIEW

**Comment by manhhung741** [comment]
Looks good to me. How is this different from the PR earlier?

**Comment by jasnow** [comment]
>> Looks good to me. How is this different from the PR earlier?

This PR does not have the side effects of my customizations - 
change .gitignore, extra Gemfile.lock files, adding dalli/redis gems, etc.

This PR is only two lines changed.

**Comment by manhhung741** [comment]
Thanks!

**Comment by jasnow** [comment]
You are welcome

**Pull request merged**
