### PR TITLE
fix T.nilable(T.untyped) errors with sorbet 0.5.9556

### LINKED ISSUE #480: Lots of T.nilable(T.untyped) errors after sorbet 0.5.9556
**Describe the bug:**

Since https://github.com/sorbet/sorbet/pull/5129 was merged, there are errors due to `T.nilable(T.untyped)` being present in the generated RBI files.

**Steps to reproduce:**
Run `bundle exec rake rails_rbi:models` after upgrading to the above sorbet version.

**Expected behavior:**
There should be no errors.

**Versions:**

- Ruby: any
- Rails: any
- Sorbet: >= 0.5.9556
- Sorbet-Rails: any

### PR DESCRIPTION
**Pull request by ashkulz**
fixes #480 -- caused by sorbet/sorbet#5129

### CODE REVIEW

**Comment by ghiculescu** [comment]
@ashkulz thank you for the PR, could you please update the tests?

**Comment by ashkulz** [comment]
@ghiculescu sorry about that, will push up a fix today :see_no_evil:

**Comment by ashkulz** [comment]
@ghiculescu that failure has been fixed, it has the same error which is present on `master`.

**Comment by klardotsh** [comment]
any chance a new stable release could be cut and released to rubygems with this included? we're currently modifying RBI files by hand to fix this issue in our codebase, this would be super helpful! cheers~

**Comment by ghiculescu** [comment]
In the meantime we have just been using the gem from the `master` branch.

**Comment by ashkulz** [comment]
@klardotsh this gem [automatically publishes to RubyGems](https://github.com/chanzuckerberg/sorbet-rails/actions/workflows/publish-gem.yml) on every commit. The CI/publish failure was fixed in #484 and you can see there have been [releases on RubyGems](https://rubygems.org/gems/sorbet-rails) (0.7.31 and 0.7.32) which include this change. We had to modify some other internal plugins we use to fix this Sorbet error, but that's nothing related to this repo :man_shrugging: 

@ghiculescu I'm not sure why you'd use `master` when the releases were published by your merges :thinking:

**Comment by klardotsh** [comment]
ah, my bad, I was looking at GitHub releases as a proxy for RubyGems, rather than looking directly at RG. that's my bad, thanks for pointing me in the right direction!

**Pull request merged**
